# Generated by Django 6.0.2 on 2026-02-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(help_text='Short bio for the hero section')),
                ('about_bio', models.TextField(blank=True, help_text='Extended bio for the About page')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills (legacy field)')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(default='Full Stack Developer', help_text='Role/title shown in hero section', max_length=200)),
                ('resume', models.URLField(blank=True, help_text='Paste your Google Drive share link (e.g. https://drive.google.com/file/d/.../view). Visitors will be able to view and download the PDF.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
