# Generated by Django 6.0.2 on 2026-02-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_profile_profile_description_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_description',
        ),
    ]
