# Generated by Django 6.0.2 on 2026-02-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_remove_profile_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Full Stack Developer', help_text='Comma-separated roles for animated hero section (e.g. Backend Dev, Data Scientist)', max_length=200),
        ),
    ]
