# Generated by Django 6.0.2 on 2026-02-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_contactmessage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
