# Generated by Django 6.0.2 on 2026-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Certification', 'Certification'), ('Hackathon', 'Hackathon'), ('Award', 'Award'), ('Recognition', 'Recognition'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date', models.DateField()),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
