# Generated by Django 6.0.2 on 2026-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='certificate_image',
        ),
        migrations.AddField(
            model_name='achievement',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
