# Generated by Django 6.0.2 on 2026-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements_app', '0002_remove_achievement_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
